### ISSUE TITLE
config file resets

### ISSUE THREAD

**Issue by JasonMFults** [mdhiggins/plexautoskip-docker#2]
When docker engine restarts it reinitializes the config file and I have to reinput all the information. am I doing something wrong?

**Comment by mdhiggins** [comment]
Are you not mounting your config file to a permanent store?

**Comment by JasonMFults** [comment]
Perhaps not. I'm not sure. I have my Plex server running on windows and I use docker desktop for this and overseer

**Comment by mdhiggins** [comment]
Docker 101, gotta mount things you want to persist to a persistent store or it'll get erased every time the container is rebuilt

https://docs.docker.com/storage/volumes/

```yml
    volumes:
      - /opt/appdata/plexautoskip:/config
```

**Comment by JasonMFults** [comment]
I figured it out. I had to change the file path in the compose file from the default provided.

**Comment by JasonMFults** [comment]
Yeah so for some reason it's not creating a volume it is binding mounting to a location that doesn't exist
